org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
kotlin.incremental=false
systemProp.java.net.preferIPv4Stack=true
android.useAndroidX=true
android.enableJetifier=true
android.builder.sdk.download=true

